<a href="https://colab.research.google.com/github/valeria-edulabs/ai-experts/blob/main/meeting11/Pandas_EDA_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import seaborn as sns

sns.set(rc={'figure.figsize':(11.7,8.27)})

In [ ]:
from matplotlib import rcParams

# figure size in inches
rcParams['figure.figsize'] = 11.7,8.27

## Loading data + Basic Pandas types
120 years of Olympic history: athletes and results
basic bio data on athletes and medal results from Athens 1896 to Rio 2016
https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results

In [ ]:
type(pd)

module

In [ ]:
df = pd.read_csv('https://storage.googleapis.com/ai-experts/datasets/athlete_events.csv')

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

## Other options to create / load dataframe

In [ ]:
data = {
    'name': ['Sivan', 'Moshe', 'Dina'],
    'math': [76, 98, 99],
    'english': [89, 79, 100]
}

In [ ]:
test_df = pd.DataFrame(data)

In [ ]:
test_df

In [ ]:
series = pd.Series([1, 13, 14, 23], dtype=int, name='grades')

In [ ]:
series

In [ ]:
test_df['new_grades'] = series

In [ ]:
test_df

## Basic summary methods

In [ ]:
type(df['City'])

pandas.core.series.Series

In [ ]:
df.head(10)

In [ ]:
df.tail(70)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   ID      271116 non-null  int64
 1   Name    271116 non-null  object
 2   Sex     271116 non-null  object
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object
 7   NOC     271116 non-null  object
 8   Games   271116 non-null  object
 9   Year    271116 non-null  int64
 10  Season  271116 non-null  object
 11  City    271116 non-null  object
 12  Sport   271116 non-null  object
 13  Event   271116 non-null  object
 14  Medal   39783 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB

In [ ]:
df.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

In [ ]:
len(df)

271116

In [ ]:
df.shape

(271116, 15)

## Columns selection

In [ ]:
df.head(3)

In [ ]:
# single column
# print(df['Age'])
# df[df['Age'] == 97]

In [ ]:
df['Age']

0         24.0
1         23.0
2         24.0
3         34.0
4         21.0
          ...
271111    29.0
271112    27.0
271113    27.0
271114    30.0
271115    34.0
Name: Age, Length: 271116, dtype: float64

In [ ]:
df[['Age']]

         Age
0       24.0
1       23.0
2       24.0
3       34.0
4       21.0
...      ...
271111  29.0
271112  27.0
271113  27.0
271114  30.0
271115  34.0

[271116 rows x 1 columns]

In [ ]:
df[['Age', 'Weight', 'Height']]

In [ ]:
df.Age

0         24.0
1         23.0
2         24.0
3         34.0
4         21.0
          ...
271111    29.0
271112    27.0
271113    27.0
271114    30.0
271115    34.0
Name: Age, Length: 271116, dtype: float64

In [ ]:
df[['Age','City']]

In [ ]:
# not working
df['Age', 'City']

In [ ]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

## Indexing

In [ ]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [ ]:
df1

,ID,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
Name,,,,,,,,,,,,,,
A Dijiang,1,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
A Lamusi,2,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
Gunnar Nielsen Aaby,3,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
Edgar Lindenau Aabye,4,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
Christine Jacoba Aaftink,5,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Andrzej ya,135569,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
Piotr ya,135570,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
Piotr ya,135570,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
Tomasz Ireneusz ya,135571,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
Tomasz Ireneusz ya,135571,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [ ]:
df1 = df.set_index("Name")

In [ ]:
df1

,ID,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
Name,,,,,,,,,,,,,,
A Dijiang,1,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
A Lamusi,2,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
Gunnar Nielsen Aaby,3,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
Edgar Lindenau Aabye,4,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
Christine Jacoba Aaftink,5,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Andrzej ya,135569,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
Piotr ya,135570,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
Piotr ya,135570,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
Tomasz Ireneusz ya,135571,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
Tomasz Ireneusz ya,135571,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

## Row selection by order

In [ ]:
row = df1.iloc[1]

In [ ]:
type(row)

pandas.core.series.Series

In [ ]:
row.index

Index(['ID', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games', 'Year',
       'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')

In [ ]:
df1.iloc[10:20:2]

,ID,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
Name,,,,,,,,,,,,,,
Per Knut Aaland,6,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
Per Knut Aaland,6,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
Per Knut Aaland,6,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
Per Knut Aaland,6,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
John Aalberg,7,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN

In [ ]:
df1.iloc[[2, 5]]

## Index and Rows Selection

In [ ]:
df1.loc["Piotr ya"]

,ID,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
Name,,,,,,,,,,,,,,
Piotr ya,135570,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
Piotr ya,135570,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

In [ ]:
df1.loc[3]

In [ ]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [ ]:
df.index = list(range(10, 10 + 271116))

In [ ]:
df

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df.drop(columns=["index"])

In [ ]:
df.reset_index()

In [ ]:
df.set_index(["Year", "Sex"]).loc[("F")]

In [ ]:
df.set_index(["Year", "Sex"]).loc[(2000, "F")]

In [ ]:
df.set_index("Name", inplace=True)

In [ ]:
df.loc["Christine Jacoba Aaftink", "Age"]

Name
Christine Jacoba Aaftink    21.0
Christine Jacoba Aaftink    21.0
Christine Jacoba Aaftink    25.0
Christine Jacoba Aaftink    25.0
Christine Jacoba Aaftink    27.0
Christine Jacoba Aaftink    27.0
Name: Age, dtype: float64

In [ ]:
df.loc["Christine Jacoba Aaftink", ["Age", "Year"]]

                           Age  Year
Name
Christine Jacoba Aaftink  21.0  1988
Christine Jacoba Aaftink  21.0  1988
Christine Jacoba Aaftink  25.0  1992
Christine Jacoba Aaftink  25.0  1992
Christine Jacoba Aaftink  27.0  1994
Christine Jacoba Aaftink  27.0  1994

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df.reset_index().loc[]

In [ ]:
df.set_index("Name")

In [ ]:
df.loc[10010:10000:-1, ["Age"]]

        Age
10010  28.0
10009  25.0
10008  19.0
10007   NaN
10006   NaN
10005  21.0
10004  21.0
10003  21.0
10002  21.0
10001  21.0
10000  21.0

In [ ]:
df.loc[2:20:4]

In [ ]:
df.loc[20:2:-1]

In [ ]:
df.loc[[1,7]]

In [ ]:
df

In [ ]:
df1 = df.set_index('Name')

In [ ]:
df1

In [ ]:
df1.loc['Piotr ya']

In [ ]:
df1.iloc['Piotr ya']

In [ ]:
df1.loc[0]

In [ ]:
df1.iloc[-2]

In [ ]:
df1

In [ ]:
df.set_index('Name', inplace=True)

In [ ]:
df1

In [ ]:
df1.iloc[2]

In [ ]:
df1.loc['Christine Jacoba Aaftink']

In [ ]:
df1['City']

In [ ]:
df1['City'].iloc[2]

In [ ]:
df1.iloc[3]

In [ ]:
df1.loc['Piotr ya', 'Age']

In [ ]:
df1.reset_index(inplace=True)

In [ ]:
df1

In [ ]:
df1 = df.set_index(['City', 'Year']).sort_index()

In [ ]:
df1.loc['Albertville']

In [ ]:
df.set_index(['City', 'Year']).index

In [ ]:
df1.index

In [ ]:
df1

In [ ]:
df1.reset_index(inplace=True)

In [ ]:
df1

## Selection by index and columns

In [ ]:
df['Age']

In [ ]:
df.loc[10:20, ['Age', 'Name']]

In [ ]:
df.loc[10:20, :]

In [ ]:
df.iloc[10:20, 2:3]

## Copy

In [ ]:
my_df = df.copy(deep=True)

In [ ]:
my_df = df

In [ ]:
# my_df.set_index('Age', inplace=True)

## Element-wise Operations

In [ ]:
df['Age'] + 5

In [ ]:
df[['Age', 'Weight', 'Height']] + 100

In [ ]:
df[['City']] + '100'

## Masks and filter

In [ ]:
df['Age'] == 10

0         False
1         False
2         False
3         False
4         False
          ...
271111    False
271112    False
271113    False
271114    False
271115    False
Name: Age, Length: 271116, dtype: bool

In [ ]:
df[(df['Age'] == 10) | (df['Age'] > 80)]

In [ ]:
df[df["Age"]]

In [ ]:
df[['Age']] == 10

In [ ]:
df[['Height', 'Weight']] == 100

In [ ]:
df != 100

In [ ]:
df[df['Age'] == 10]

In [ ]:
df['Age'] >=80

In [ ]:
df.loc[[10, 80]]

In [ ]:
df[df['Age'] >=80]

In [ ]:
mask = (df['Age'] > 30) & (df['Team'] == 'Israel')

In [ ]:
df[mask]

In [ ]:
df[(df['Team'] == 'Israel') & (~df['Medal'].isna())].sort_values("Age")

,Name,ID,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
73099,Gal Fridman,37163,M,20.0,183.0,68.0,Israel,ISR,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Men's Windsurfer,Bronze
270589,Shahar Zubari,135332,M,21.0,177.0,68.0,Israel,ISR,2008 Summer,2008,Summer,Beijing,Sailing,Sailing Men's Windsurfer,Bronze
223070,Shay-Oren Smadja,112033,M,22.0,NaN,NaN,Israel,ISR,1992 Summer,1992,Summer,Barcelona,Judo,Judo Men's Lightweight,Bronze
8686,Yael Arad,4771,F,25.0,NaN,NaN,Israel,ISR,1992 Summer,1992,Summer,Barcelona,Judo,Judo Women's Half-Middleweight,Silver
123081,Michael (-Mikhail) Kolganov,62204,M,25.0,185.0,89.0,Israel,ISR,2000 Summer,2000,Summer,Sydney,Canoeing,"Canoeing Men's Kayak Singles, 500 metres",Bronze
211004,Or Sasson,105958,M,25.0,193.0,120.0,Israel,ISR,2016 Summer,2016,Summer,Rio de Janeiro,Judo,Judo Men's Heavyweight,Bronze
78166,Yarden Gerbi,39695,F,27.0,169.0,63.0,Israel,ISR,2016 Summer,2016,Summer,Rio de Janeiro,Judo,Judo Women's Half-Middleweight,Bronze
268223,"Ariel ""Arik"" Ze'evi",134194,M,27.0,186.0,100.0,Israel,ISR,2004 Summer,2004,Summer,Athina,Judo,Judo Men's Half-Heavyweight,Bronze
73100,Gal Fridman,37163,M,28.0,183.0,68.0,Israel,ISR,2004 Summer,2004,Summer,Athina,Sailing,Sailing Men's Windsurfer,Gold

## Column addition

In [ ]:
df['Is_Child'] = df['Age'] <= 16

In [ ]:
df[df["Age"].isna()]

In [ ]:
(df['Age'] <= 16).loc[147]

False

In [ ]:
df

In [ ]:
df[df["Is_Child"]]

In [ ]:
df[["Age10", "Height10"]] = df[["Age", "Height"]] + 10

## Column deletion

In [ ]:
# drop - both columns and rows
df.drop(columns=['Is_Child'], inplace=True)

In [ ]:
df.index

In [ ]:
df.drop(df.index[30:40])

## Columns update

In [ ]:
df1 = df.copy()

In [ ]:
df1['Age'] = df1['Age'] + 10

In [ ]:
#astype
# df['Sex'] = 'Female' if df['Sex'] == 'F' else 'Male'
df.dropna(inplace=True)
new_age = df['Age'].astype(int)

In [ ]:
df

In [ ]:
df['Age'] = df['Age'].astype(int)

In [ ]:
df['Age'] = df[~df['Age'].isna()]['Age'].astype(int)

In [ ]:
df

In [ ]:
df[~df['Age'].isna()]['Age'].astype(int)