In [3]:
# Imports and configurations
import datetime
from math import sqrt

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler

#  (high-level, simple to use)
import plotly.express as px
# (low-level, highly customizable)
import plotly.graph_objects as go

from scipy import stats

# Set Plotly as Pandas plotting backend

pd.options.plotting.backend = "plotly"
# Read the data

In [2]:
data_path = "https://storage.googleapis.com/biosense-ml-data/insurance.csv"
data_path_clean = "https://storage.googleapis.com/biosense-ml-data/insurance_clean.csv"
data_path_clean_no_outliers = "https://storage.googleapis.com/biosense-ml-data/insurance_clean_no_outliers.csv"

column_definitions = {
    'age': np.int8,
    'sex': 'category',
    'bmi': np.float32,
    'children': np.int8,
    'smoker': bool,
    'region': 'category',
    'charges': np.float32
}
df = pd.read_csv(data_path_clean, dtype=column_definitions)

In [4]:
df

      age     sex        bmi  children  smoker     region       charges
0      19  female  27.900000         0    True  southwest  16884.923828
1      18    male  33.770000         1   False  southeast   1725.552246
2      28    male  33.000000         3   False  southeast   4449.461914
3      33    male  22.705000         0   False  northwest  21984.470703
4      32    male  28.879999         0   False  northwest   3866.855225
...   ...     ...        ...       ...     ...        ...           ...
1334   50    male  30.969999         3   False  northwest  10600.547852
1335   18  female  31.920000         0   False  northeast   2205.980713
1336   18  female  36.849998         0   False  southeast   1629.833496
1337   21  female  25.799999         0   False  southwest   2007.944946
1338   61  female  29.070000         0    True  northwest  29141.359375

[1339 rows x 7 columns]

**Exercise: Implement KNNRegressor**

- Implement KNeighborsRegressor and use Cross-Validation to find best parameters
- Try different distance metrics, different K, and maybe other params to find the best fit
- After you have the best performing model, answer the following question: given a female from northeast, non-smoking, 2 children, 25 years old with bmi of 24, how much pays for the insurance another person from the dataset that is most similar to the given person?